# This setting ensures the safe removal of player skins.
# With online-mode being false, Premium Accounts are not needed to join the server.
# The value should be the same as the value in the server.properties
# If online-mode is set to false, the plugin will not try to find the default skin of the player
online-mode: true

# Whether the plugin should download default Skin Packs
# If set to false, they will not be included
# Also will not cache them even if they are stored within the local files
downloadBaseSkins: true

# This is a service responsible for different types of placeholders
# It is useful for handling ranks, for example, when a user wants their rank to hide on disguise
display:
  # The prefix is equivalent to what the %dp_prefix% value will show
  # -- Depending on whether the user is currently disguised or not,
  # -- the prefix will either be the value in disguised, or default, respectively
  # -----------------------------------------------------------------------------
  # Both of these values support colors using the '&' character.
  # -----------------------------------------------------------------------------
  prefix:
    # Value shown when the player is not disguised
    default: "%vault_rank%"

    # Value shown when the player is disguised
    disguised: ""

# This property will enable the integration with TAB plugin written by NEZNAMY.
# Use this if you want to have different player prefixes depending on if the player is disguised
# or not.
tab:
  autoRank: true
  enabled: false

  # This will automatically set the prefix to whatever the value between the parentheses is
  # - For example you want to hide your owner rank when you are disguised, and only show MVP rank from rank manager above,
  # - you would set the placeholder to %dp_rank%.
  #
  # -- It supports both colors and placeholders.
  # When using placeholders make sure that the expansion of the placeholder is enabled.
  # If you want the prefix to be blank leave an empty string, otherwise set the enabled value to false.
  disguise-prefix: "%dp_rank%"