# +----------------------------------------------------------------------------------------------+ #
# |                                                                                              | #
# |                                      STORAGE SETTINGS                                        | #
# |                                                                                              | #
# |                       Defines how the plugin should interact with the database               | #
# |                                                                                              | #
# +----------------------------------------------------------------------------------------------+ #

# These are basic settings allowing us to successfully connect to a database.
# - In order to apply this, "database.enabled" key must be set to true.
# - Make sure to correct the credentials, in order to avoid any errors. (For example wrong password, or hostname)
database:
  enabled: false
  host: "localhost:3306/disguise"
  customJdbcUrl: ""
  driverClass: ""
  username: "root"
  password: ""

  # HikariCP is a library which allows us to control and cache the connections to the database
  # These settings should not be changed, unless you have an idea of what you are doing
  # - More about Hikari: https://github.com/brettwooldridge/HikariCP
  hikari-pool:
    # This property controls the maximum number of milliseconds that a client (that's you) will wait for a connection from the pool.
    # Lowest acceptable connection timeout is 250 ms. Default: 30000 (30 seconds)
    connection-timeout: 30000 # This means that the timeout will be 30 seconds

    # This property controls how frequently HikariCP will attempt to keep a connection alive,
    # in order to prevent it from being timed out by the database or network infrastructure.
    # When the time arrives for a "keep-alive" against a given connection, that connection will be removed from the pool, "pinged", and then returned to the pool.
    # Typically, the duration out-of-the-pool should be measured in single digit milliseconds or even sub-millisecond, and therefore should have little or no noticeable performance impact.
    # The minimum allowed value is 30000ms (30 seconds), but a value in the range of minutes is most desirable. Default: 0 (disabled)
    keep-alive-time: 0

    # This property controls the minimum number of idle connections that HikariCP tries to maintain in the pool.
    # For maximum performance and responsiveness to spike demands, we recommend not setting this value and instead allowing HikariCP to act as a fixed size connection pool.
    # Default: same as maximumPoolSize
    minimum-idle: 10

    # This property controls the maximum size that the pool is allowed to reach, including both idle and in-use connections.
    # Basically this value will determine the maximum number of actual connections to the database backend.
    # Default: 10
    maximum-pool-size: 10

    # This property controls the maximum lifetime of a connection in the pool.
    # An in-use connection will never be retired, only when it is closed will it then be removed.
    # Minimum allowed value is 30000ms (30 seconds).
    # Default: 1800000 (30 minutes)
    maximum-lifetime: 1800000


# This setting ensures the safe removal of player skins.
# With online-mode being false, Premium Accounts are not needed to join the server.
# The value should be the same as the value in the server.properties
# If online-mode is set to false, the plugin will not try to find the default skin of the player
online-mode: true

# Whether the plugin should download default Skin Packs
# If set to false, they will not be included
# Also will not cache them even if they are stored within the local files
downloadBaseSkins: true

# This is a service responsible for different types of placeholders
# It is useful for handling ranks, for example, when a user wants their rank to hide on disguise
display:
  # The prefix is equivalent to what the %dp_prefix% value will show
  # -- Depending on whether the user is currently disguised or not,
  # -- the prefix will either be the value in disguised, or default, respectively
  # -----------------------------------------------------------------------------
  # Both of these values support colors using the '&' character.
  # -----------------------------------------------------------------------------
  prefix:
    # Value shown when the player is not disguised
    default: "%vault_rank%"

    # Value shown when the player is disguised
    disguised: ""

# This property will enable the integration with TAB plugin written by NEZNAMY.
# Use this if you want to have different player prefixes depending on if the player is disguised
# or not.
tab:
  autoRank: true
  enabled: false

  # This will automatically set the prefix to whatever the value between the parentheses is
  # - For example you want to hide your owner rank when you are disguised, and only show MVP rank from rank manager above,
  # - you would set the placeholder to %dp_rank%.
  #
  # -- It supports both colors and placeholders.
  # When using placeholders make sure that the expansion of the placeholder is enabled.
  # If you want the prefix to be blank leave an empty string, otherwise set the enabled value to false.
  disguise-prefix: "%dp_rank%"