# This setting ensures the safe removal of player skins.
# With online-mode being false, Premium Accounts are not needed to join the server.
# The value should be the same as the value in the server.properties
# If online-mode is set to false, the plugin will not try to find the default skin of the player
online-mode: true


# Whether the plugin should download default Skin Packs
# If set to false, they will not be included
# Also will not cache them even if they are stored within the local files
downloadBaseSkins: true