# Includes basic nick settings, that apply when using /nick or /disguise
nick:
  # This is the pattern used to create random nicks when doing /disguise
  # a - vowel (a, e, i, o, u)
  # A - consonant
  # Values that are between ||, for example |aAa| are optional and will be randomly generated.
  # For example, the pattern: "AaAaA|aA|" will always contain at least 5 characters and a maximum of 7, where the pattern is
  #   Consonant - Vowel - Consonant - Vowel - Consonant |Vowel - Consonant|
  pattern: "AaAaA|aA|"

  # This is the minimum length any player can use when setting their nick
  # Note that this cannot not be below 3
  min-length: 5

  # This is the maximum length any player can set
  # This setting may not be above 16, meaning 16 is the maximum
  max-length: 16

cooldowns:
  # Whether the cooldown should be enabled
  # If this feature is enabled, you can selec
  enabled: false

  # The length of the cooldown in seconds
  # - in how many seconds a command can be used again after executing
  # If you wanted a longer cooldown, but are not good with maths just go to settings using /dp command in game.
  interval: 10

  # If any player has this permission, they will be able to bypass the already above set cooldowns.
  bypass: "dp.cooldown.bypass"

display:
  chat:
    # This setting overrides the chat format that is being set by default and by other plugins
    # If you are using any other ChatHandler plugin such as EssentialsChat or ChatManager this setting should be set to false
    override: false

    # Represents the format of the message displayed when a user sends a message in the chat
    # This setting supports Placeholder and Color usage
    # The format CAN be edited, but the %player_name% and %message% must also be included
    # Example formats:
    #   - "%disguise_prefix% %player_name% %message%"
    #   - "[%vault_rank%] %player_name% %message%"
    #   - "%disguise_prefix% %player_name% %disguise_suffix% %message%"
    format: "%player_name% %message%"

  # Corresponds to the Placeholder %disguise_prefix%
  # The values below represent the value of %disguise_prefix% in the states of the player
  prefix:
    # This is the value when a player is not disguised
    default: "%vault_rank%"

    # This is the value when a player is disguised
    disguised: ""

  # Corresponds to the Placeholder %disguise_suffix%
  # The values below represent the value of %disguise_suffix% in the states of the player
  suffix:
    # This is the value when a player is not disguised
    default: "*"

    # This is the value when a player is disguised
    disguised: ""

# Whether we should occasionally check for any plugin updates
# The interval is 20 minutes
update: true

# Whether bStats Metrics should be cached.
# This options is used see how many servers are using this plugin
bstats: true

# This setting ensures the safe removal of player skins.
# With online-mode being false, Premium Accounts are not needed to join the server.
# The value should be the same as the value in the server.properties
# If online-mode is set to false, the plugin will not try to find the default skin of the player
online-mode: true

# If you want data to be synced across multiple servers, use this option.
mysql:
  enabled: false

  # The host of the server
  host: "localhost"

  # The port of the server
  port: 3306

  # The database name where the data is stored
  database: "disguise_pro"

  # The username for accesing the server
  username: "root"

  # The password for accesing the server (leave blank if you don't have a password)
  password: ""

# Below is the list of worlds that have disguise toggled
# If a world is disabled, commands below may not be used by any player:
#   - /d, /rd, /und
#   - /nick, /skin
disabled-worlds:
